status = warn
name = propertiesConfig

# ??????? INFO
rootLogger.level = INFO
rootLogger.appenderRef.console.ref = Console

# ???????
appender.console.type = Console
appender.console.name = Console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss} %-5p %c{1} - %m%n

# ?? Kafka ?? DEBUG ??
logger.kafka.name = org.apache.kafka
logger.kafka.level = WARN

# ?? Flink ???? DEBUG ??
logger.flink-connector.name = org.apache.flink.connector
logger.flink-connector.level = INFO